In [34]:
import numpy as np

#data = np.zeros((3,5))

#data = np.loadtxt("input/5.1Potentialtopf")

with open("input/5.1Potentialtopf") as fp:
    aa = 0
    for line in fp:
        print('aa:',aa)
        line_coll = line.split()
        bb = 0
        for item in line_coll:
            print('bb:',bb)
            item = float(item)
            print('itemtype:',type(item))
            print(item)
            data[aa,bb] = item
            bb += 1
        aa += 1
    #data = fp.read()
    #data.split("\n")
    #print(data)
    #lines = fp.readlines()
#print(lines)
    
#data = np.loadtxt("input/123-array")
#data = np.loadtxt(fp)

#for line in data:
    #print(data)
#print(data)



aa: 0
bb: 0
itemtype: <class 'float'>
2.0


TypeError: 'str' object does not support item assignment

In [38]:
data = np.zeros((3,5), dtype=float)
with open("input/5.1Potentialtopf") as fp:
    aa = 0
    for line in fp:
        print('aa:',aa)
        line_coll = line.split()
        bb = 0
        for item in line_coll:
            print('bb:',bb)
            if not item[0] = '#':
            item = float(item)
            print('itemtype:',type(item))
            print(item)
            data[aa,bb] = item
            bb += 1
        aa += 1

aa: 0
bb: 0
itemtype: <class 'float'>
2.0
bb: 1


ValueError: could not convert string to float: '#'

In [136]:
newdata = np.zeros((7,3))
alldata = []
with open("input/5.1Potentialtopf") as fp:
    for line in fp:
        alldata.append(line.split("\n")[0])
dataline_y = 0
for dataline in alldata:
    line = (dataline.split("#")[0])
    print(line)
    for element in line.split():
        #print(element)
        #newdata[dataline_y,dataline_x] = element.strip()


SyntaxError: unexpected EOF while parsing (<ipython-input-136-99f6c240895b>, line 12)

In [179]:
alldata = []
with open("input/5.1Potentialtopf") as fp:
    for line in fp:
        alldata.append(line.strip())
dataline_y = 0
for dataline in alldata:
    alldata[dataline_y] = dataline.split("#")[0].strip().split()
    #removes annotation of input data and splits lines into lists of individual inputs
    dataline_y += 1

if alldata[3] == ['linear']:
    alldata[3] = [0]
elif alldata[3] == ['polynomial']:
    alldata[3] = [1]
elif alldata[3] == ['cspline']:
    alldata[3] = [2]
#else:
    #alldata[3] 
    #raise some kind of input error

newdata = np.zeros((len(alldata),3))
line_y = 0
for line in alldata:
    line_x = 0
    for coll in alldata[line_y]:
        newdata[line_y,line_x] = alldata[line_y][line_x]
        line_x += 1
    line_y += 1
print(newdata)


[[  2.00000000e+00   0.00000000e+00   0.00000000e+00]
 [ -2.00000000e+00   2.00000000e+00   1.99900000e+03]
 [  1.00000000e+00   5.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   0.00000000e+00   0.00000000e+00]
 [ -2.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   0.00000000e+00   0.00000000e+00]]
