In [3]:
import numpy as np
alldata = []
with open("input/5.1Potentialtopf") as fp:
    for line in fp:
        alldata.append(line.strip())
dataline_y = 0
for dataline in alldata:
    alldata[dataline_y] = dataline.split("#")[0].strip().split()
    #removes annotation of input data and splits lines into lists of individual inputs
    dataline_y += 1

if alldata[3] == ['linear']:
    alldata[3] = [0]
elif alldata[3] == ['polynomial']:
    alldata[3] = [1]
elif alldata[3] == ['cspline']:
    alldata[3] = [2]
#else:
    #alldata[3]
    #raise some kind of input error

newdata = np.zeros((len(alldata),3))
line_y = 0
for line in alldata:
    line_x = 0
    for coll in alldata[line_y]:
        newdata[line_y,line_x] = alldata[line_y][line_x]
        line_x += 1
    line_y += 1
print('input:', newdata)
#this is all just the input generator

#now to the actual stuff:


for number_of_inputs in range(0,len(points)):
        for nn in range(0, nPoint):
            if points[0,number_of_inputs] >= XX[nn]:
                #hier muss ich mir noch überlegen wie ich YY auswähle und
                #ob das so geschickt ist




    potential = np.zeros((2,nPoint))
    XX = np.linspace(xMin, xMax, nPoint, endpoint=True)
    YY = []
    delta = abs(XX[1]-XX[0])
    #test values for y in matrix
    for nn in range(0, nPoint):
        YY.append(nn)
        #statt append hier lieber die variable an stelle nn durch den
        #jeweiligen y-wert ersetzen
    for index in range(0, nPoint):
        potential[0,index] = XX[index]
        potential[1,index] = YY[index]




input: [[  2.00000000e+00   0.00000000e+00   0.00000000e+00]
 [ -2.00000000e+00   2.00000000e+00   1.99900000e+03]
 [  1.00000000e+00   5.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   0.00000000e+00   0.00000000e+00]
 [ -2.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   0.00000000e+00   0.00000000e+00]]
