In [33]:
import numpy as np
# input: potential, delta, mass
mass = 3
delta = 0.002
potential = np.array([[0, 0], [1, 1], [2, 2], [3, 3]])
V_diskr = []
for pair in potential:
    V_diskr.append(pair[1])

content = []

aa = 1 / (mass * (delta**2))

content.append(aa * V_diskr[0])
for columns in range(0, len(V_diskr)-1):   
    content.append(-0.5 * aa)
    for num in range(0, len(V_diskr)-2):
         content.append(0)
    content.append(-0.5 * aa)               
    content.append(aa * V_diskr[columns+1])
content = np.array(content)
content.shape = (len(V_diskr), len(V_diskr))
print(content)

[[      0.          -41666.66666667       0.               0.        ]
 [ -41666.66666667   83333.33333333  -41666.66666667       0.        ]
 [      0.          -41666.66666667  166666.66666667  -41666.66666667]
 [      0.               0.          -41666.66666667  250000.        ]]


In [9]:
import numpy.linalg as linalg
ew,ev = linalg.eig(content)
print(ew,ev)

[ -18786.27770529   81379.66829974  166666.66666667  251953.66503359
  352119.61103862] [[ 0.90737016 -0.40530571  0.10976426 -0.01884969  0.00178074]
 [ 0.40910659  0.79160745 -0.43905704  0.11398197 -0.01504881]
 [ 0.09529717  0.44242256  0.76834982 -0.44242256  0.09529717]
 [ 0.01504881  0.11398197  0.43905704  0.79160745 -0.40910659]
 [ 0.00178074  0.01884969  0.10976426  0.40530571  0.90737016]]


In [7]:
import solvers
xx_gauss = solvers.gaussian_eliminate(content)
print(xx_gauss)

ModuleNotFoundError: No module named 'solvers'