In [66]:
import numpy as np
alldata = []
with open("input/5.1Potentialtopf") as fp:
    for line in fp:
        alldata.append(line.strip())
dataline_y = 0
for dataline in alldata:
    alldata[dataline_y] = dataline.split("#")[0].strip().split()
    #removes annotation of input data and splits lines into lists of individual inputs
    dataline_y += 1

if alldata[3] == ['linear']:
    alldata[3] = [0]
elif alldata[3] == ['polynomial']:
    alldata[3] = [1]
elif alldata[3] == ['cspline']:
    alldata[3] = [2]
#else:
    #alldata[3]
    #raise some kind of input error

newdata = np.zeros((len(alldata),3))
line_y = 0
for line in alldata:
    line_x = 0
    for coll in alldata[line_y]:
        newdata[line_y,line_x] = alldata[line_y][line_x]
        line_x += 1
    line_y += 1
print('input:', newdata)
#this is all just the input generator

#now to the actual stuff:

import scipy.interpolate as inter
_interpolation_types = {0: 'linear', 1: 'cubic', 2: ''}
#linear, cubic, cspline

yy, xx = newdata.shape
base = newdata[5:yy+1, 0:2]
x_data = []
y_data = []

print(base)
#base = 

pointcount = 0
for item in base[0]:
    x_data.append(base[pointcount,0])
    y_data.append(base[pointcount,1])
    pointcount += 1


if newdata[3,0]:
    if newdata[3,0] == 1:
        Vx = np.polyfit(x_data, y_data, yy - 6)
    else:
        Vx = inter.CubicSpline(x_data, y_data)
else:
    Vx = inter.interp1d(x_data, y_data, kind ='linear')

potential = np.zeros((2, int(newdata[1,2]))
#np.linspace(newdata[1,0], newdata[1,1], newdata[1,2], endpoint=True)

#pointcount = 0
#for item in XX_values:
    #potential[pointcount,0] = item
    #potential[pointcount,1] = Vx(item)
    #pointcount += 1

#print(potential)

#nur zum anzeigen
xnew = np.linspace(-2, 2, num=41, endpoint=True)
                     

import matplotlib.pyplot as plt

plt.plot(x_data, y_data, 'o', xnew, Vx(xnew), '-')

plt.show()

    
    
    
    
    
    
potential = np.zeros((2,nPoint))
XX = np.linspace(xMin, xMax, nPoint, endpoint=True)
YY = []
delta = abs(XX[1]-XX[0])
    #test values for y in matrix
    
for nn in range(0, nPoint):
    YY.append(nn)
    #diese zeile kann in die nächste integriert werden 
for index in range(0, nPoint):
    potential[0,index] = XX[index]
    potential[1,index] = YY[index]




SyntaxError: invalid syntax (<ipython-input-66-fb19201c7fde>, line 74)

In [72]:
import numpy as np
alldata = []
with open("input/5.1Potentialtopf") as fp:
    for line in fp:
        alldata.append(line.strip())
dataline_y = 0
for dataline in alldata:
    alldata[dataline_y] = dataline.split("#")[0].strip().split()
    #removes annotation of input data and splits lines into lists of individual inputs
    dataline_y += 1

if alldata[3] == ['linear']:
    alldata[3] = [0]
elif alldata[3] == ['polynomial']:
    alldata[3] = [1]
elif alldata[3] == ['cspline']:
    alldata[3] = [2]
#else:
    #alldata[3]
    #raise some kind of input error

newdata = np.zeros((len(alldata),3))
line_y = 0
for line in alldata:
    line_x = 0
    for coll in alldata[line_y]:
        newdata[line_y,line_x] = alldata[line_y][line_x]
        line_x += 1
    line_y += 1
print('input:', newdata)
#this is all just the input generator

#now to the actual stuff:

import scipy.interpolate as inter
_interpolation_types = {0: 'linear', 1: 'cubic', 2: ''}
#linear, cubic, cspline

yy, xx = newdata.shape
base = newdata[5:yy+1, 0:2]
x_data = []
y_data = [] 

pointcount = 0
for item in base[0]:
    x_data.append(base[pointcount,0])
    y_data.append(base[pointcount,1])
    pointcount += 1

#check if that works with floats
if newdata[3,0]:
    if newdata[3,0] == 1:
        Vx = np.polyfit(x_data, y_data, yy - 6)
    else:
        Vx = inter.CubicSpline(x_data, y_data)
else:
    Vx = inter.interp1d(x_data, y_data, kind ='linear')

potential = np.zeros((int(newdata[1,2]),2))
XX_values = np.linspace(newdata[1,0], newdata[1,1], newdata[1,2], endpoint=True)

pointcount = 0
for item in XX_values:
    potential[pointcount,0] = item
    potential[pointcount,1] = Vx(item)
    pointcount += 1
print(potential)

input: [[  2.00000000e+00   0.00000000e+00   0.00000000e+00]
 [ -2.00000000e+00   2.00000000e+00   1.99900000e+03]
 [  1.00000000e+00   5.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   0.00000000e+00   0.00000000e+00]
 [ -2.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   0.00000000e+00   0.00000000e+00]]
[[-2.        0.      ]
 [-1.997998  0.      ]
 [-1.995996  0.      ]
 ..., 
 [ 1.995996  0.      ]
 [ 1.997998  0.      ]
 [ 2.        0.      ]]


/usr/lib/python3/dist-packages/ipykernel_launcher.py:60: DeprecationWarning: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.


In [8]:
import numpy as np
alldata = []
with open("input/5.1Potentialtopf") as fp:
    for line in fp:
        alldata.append(line.strip())
dataline_y = 0
for dataline in alldata:
    alldata[dataline_y] = dataline.split("#")[0].strip().split()
    #removes annotation of input data and splits lines into lists of individual inputs
    dataline_y += 1

if alldata[3] == ['linear']:
    alldata[3] = [0]
elif alldata[3] == ['polynomial']:
    alldata[3] = [1]
elif alldata[3] == ['cspline']:
    alldata[3] = [2]
#else:
    #alldata[3]
    #raise some kind of input error

newdata = np.zeros((len(alldata),3))
line_y = 0
for line in alldata:
    line_x = 0
    for coll in alldata[line_y]:
        newdata[line_y,line_x] = alldata[line_y][line_x]
        line_x += 1
    line_y += 1
print('input:', newdata)
#this is all just the input generator

#now to the actual stuff:

import scipy.interpolate as inter
yy, xx = newdata.shape
base = newdata[5:yy+1, 0:2]
x_data = []
y_data = [] 

pointcount = 0
for item in base[0]:
    x_data.append(base[pointcount,0])
    y_data.append(base[pointcount,1])
    pointcount += 1

#check if that works with floats
if newdata[3,0]:
    if newdata[3,0] == 1.0:
        Vx = np.polyfit(x_data, y_data, yy - 6)
    else:
        Vx = inter.CubicSpline(x_data, y_data)
else:
    Vx = inter.interp1d(x_data, y_data, kind ='linear')

potential = np.zeros((int(newdata[1,2]),2))
XX_values = np.linspace(int(newdata[1,0]), int(newdata[1,1]), int(newdata[1,2]), endpoint=True)
delta = XX_values[0] - XX_values[1]

pointcount = 0
for item in XX_values:
    potential[pointcount,0] = item
    potential[pointcount,1] = Vx(item)
    pointcount += 1

print(potential, delta)

input: [[  2.00000000e+00   0.00000000e+00   0.00000000e+00]
 [ -2.00000000e+00   2.00000000e+00   1.99900000e+03]
 [  1.00000000e+00   5.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   0.00000000e+00   0.00000000e+00]
 [ -2.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   0.00000000e+00   0.00000000e+00]]
[[-2.        0.      ]
 [-1.997998  0.      ]
 [-1.995996  0.      ]
 ..., 
 [ 1.995996  0.      ]
 [ 1.997998  0.      ]
 [ 2.        0.      ]] -0.002002002002
